// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPd5K34AG0AXG1C0sn0r23pTayroc-mnc',
    appId: '1:277353577623:web:43eef4ac3d46f69896bdd2',
    messagingSenderId: '277353577623',
    projectId: 'chat-app-kouseina',
    authDomain: 'chat-app-kouseina.firebaseapp.com',
    storageBucket: 'chat-app-kouseina.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC63Nm18ltC-NbZSmCRVWVWkF1dmQMl1pY',
    appId: '1:277353577623:android:b5d5a49caa897ded96bdd2',
    messagingSenderId: '277353577623',
    projectId: 'chat-app-kouseina',
    storageBucket: 'chat-app-kouseina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPjCKgaIjEYE2VHZ-GoyRwyaZDrKkKAH4',
    appId: '1:277353577623:ios:6f66e59c26f560da96bdd2',
    messagingSenderId: '277353577623',
    projectId: 'chat-app-kouseina',
    storageBucket: 'chat-app-kouseina.appspot.com',
    androidClientId: '277353577623-bvmsapmeng31lmkq2mie6d5ukmaqtkhm.apps.googleusercontent.com',
    iosClientId: '277353577623-k954uhhv7ljinteftm1oos09p1f0ge6v.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
