// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPd5K34AG0AXG1C0sn0r23pTayroc-mnc',
    appId: '1:277353577623:web:43eef4ac3d46f69896bdd2',
    messagingSenderId: '277353577623',
    projectId: 'chat-app-kouseina',
    authDomain: 'chat-app-kouseina.firebaseapp.com',
    storageBucket: 'chat-app-kouseina.appspot.com',
    measurementId: 'G-NY6CD9LJE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4dAL8bfu8aNyQJcyzfvvjsYiJRbnQBE',
    appId: '1:277353577623:android:c596f016a5fe644096bdd2',
    messagingSenderId: '277353577623',
    projectId: 'chat-app-kouseina',
    storageBucket: 'chat-app-kouseina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ULuFT-M2O6Ee-kFNLt6La_I4iK8L-oY',
    appId: '1:277353577623:ios:e5483ea2cd32b5e896bdd2',
    messagingSenderId: '277353577623',
    projectId: 'chat-app-kouseina',
    storageBucket: 'chat-app-kouseina.appspot.com',
    androidClientId: '277353577623-4dcjskdm4j64h26l1t435iec73qilt3m.apps.googleusercontent.com',
    iosClientId: '277353577623-0goojvmcj0bgd98q0g5l14b6ugh7m33g.apps.googleusercontent.com',
    iosBundleId: 'com.kouseina.nimbrung',
  );
}
